# Generated by Django 4.2.13 on 2024-05-25 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=2000, validators=[django.core.validators.RegexValidator(message='Password must be 3-30 characters long and can only contain letters, numbers, and underscores.', regex='^[\\w]{3,30}$')]),
        ),
    ]
