# Generated by Django 4.2.13 on 2024-05-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0002_customer_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField()),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('price_currency', models.CharField(max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField()),
                ('order_status', models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('SHIPPED', 'SHIPPED'), ('AT_SORTING_FACILITY', 'AT_SORTING_FACILITY'), ('DELIVERY_ON_THE_WAY', 'DELIVERY_ON_THE_WAY')], max_length=200)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount_paid', models.FloatField()),
                ('payment_currency', models.CharField(max_length=10)),
                ('delivery_address', models.CharField(max_length=2000)),
                ('payment_status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
    ]
