# Generated by Django 4.2.13 on 2024-05-22 09:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_status', models.CharField(choices=[('DELIVERED', 'DELIVERED'), ('SHIPPED', 'SHIPPED'), ('AT_SORTING_FACILITY', 'AT_SORTING_FACILITY'), ('DELIVERY_ON_THE_WAY', 'DELIVERY_ON_THE_WAY'), ('ORDER_PLACED', 'ORDER_PLACED')], max_length=200)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('total_amount_paid', models.FloatField()),
                ('delivery_address', models.CharField(max_length=2000)),
                ('payment_status', models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETED', 'COMPLETED')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
        ),
    ]
