# Generated by Django 4.2.13 on 2024-05-22 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_currency',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price_currency',
        ),
    ]
