# Generated by Django 4.2.13 on 2024-05-22 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
